```sql
-- Create database and schemas for industrial telemetry
CREATE DATABASE IF NOT EXISTS OPTIPULSE_DB;
CREATE SCHEMA IF NOT EXISTS TELEMETRY_SCHEMA;

-- Structured Table: IoT Sensor Telemetry
CREATE OR REPLACE TABLE IOT_SENSOR_STREAM (
    SENSOR_ID VARCHAR(50),
    MACHINE_ID VARCHAR(50),
    RECORD_TIMESTAMP TIMESTAMP_NTZ,
    VIBRATION_MM_S FLOAT,
    TEMPERATURE_C FLOAT,
    PRESSURE_BAR FLOAT,
    STATUS VARCHAR(20)
);

-- Structured Table: OEE Metrics Table
CREATE OR REPLACE TABLE MACHINE_OEE_METRICS (
    MACHINE_ID VARCHAR(50),
    CALC_DATE DATE,
    AVAILABILITY FLOAT,
    PERFORMANCE FLOAT,
    QUALITY FLOAT,
    OEE_SCORE FLOAT
);
